import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy | Bencos Research Solutions",
  description:
    "How Bencos Research Solutions collects, uses, and protects your personal and research data.",
}

// Hero background image — swap the src to change it.
const HERO_IMAGE = "/images/image 502.webp"

const lastUpdated = "July 2026"

type Block =
  | { type: "p"; text: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[] }
  | { type: "defs"; items: { term: string; text: string }[] }

interface Section {
  heading: string
  blocks: Block[]
}

const sections: Section[] = [
  {
    heading: "Introduction",
    blocks: [
      {
        type: "p",
        text: "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
      },
      {
        type: "p",
        text: "We use Your Personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.",
      },
    ],
  },
  {
    heading: "Interpretation and Definitions",
    blocks: [
      { type: "h3", text: "Interpretation" },
      {
        type: "p",
        text: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
      },
      { type: "h3", text: "Definitions" },
      { type: "p", text: "For the purposes of this Privacy Policy:" },
      {
        type: "defs",
        items: [
          { term: "Account", text: "means a unique account created for You to access our Service or parts of our Service." },
          { term: "Company", text: "(referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Peptech Biosciences Ltd, 905, 9th Floor, Bigjos Tower, Netaji Subhash Place, New Delhi, Delhi 110034." },
          { term: "Cookies", text: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
          { term: "Country", text: "refers to: Delhi, India." },
          { term: "Device", text: "means any device that can access the Service such as a computer, a cellphone or a digital tablet." },
          { term: "Personal Data", text: "is any information that relates to an identified or identifiable individual." },
          { term: "Service", text: "refers to the Website." },
          { term: "Service Provider", text: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
          { term: "Usage Data", text: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
          { term: "You", text: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." },
        ],
      },
    ],
  },
  {
    heading: "Collecting and Using Your Personal Data",
    blocks: [
      { type: "h3", text: "Personal Data" },
      {
        type: "p",
        text: "While using Our Service, we may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
      },
      {
        type: "list",
        items: [
          "Email address",
          "First name and last name",
          "Phone number",
          "Address, State, Province, ZIP/Postal code, City",
          "Usage Data",
        ],
      },
      { type: "h3", text: "Usage Data" },
      { type: "p", text: "Usage Data is collected automatically when using the Service." },
      {
        type: "p",
        text: "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
      },
      {
        type: "p",
        text: "When You access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device You use, your mobile device unique ID, the IP address of Your mobile device, your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
      },
      {
        type: "p",
        text: "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
      },
      { type: "h3", text: "Tracking Technologies and Cookies" },
      {
        type: "p",
        text: "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.",
      },
    ],
  },
  {
    heading: "Use of Your Personal Data",
    blocks: [
      { type: "p", text: "The Company may use Personal Data for the following purposes:" },
      {
        type: "defs",
        items: [
          { term: "To provide and maintain our Service", text: "including to monitor the usage of our Service." },
          { term: "To manage Your Account", text: "to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user." },
          { term: "For the performance of a contract", text: "the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service." },
          { term: "To contact You", text: "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation." },
          { term: "To provide You with news and offers", text: "special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information." },
          { term: "To manage Your requests", text: "To attend and manage Your requests to Us." },
          { term: "For business transfers", text: "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred." },
          { term: "For other purposes", text: "We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience." },
        ],
      },
      { type: "p", text: "We may share Your personal information in the following situations:" },
      {
        type: "defs",
        items: [
          { term: "With Service Providers", text: "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You." },
          { term: "For business transfers", text: "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company." },
          { term: "With Affiliates", text: "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us." },
          { term: "With business partners", text: "We may share Your information with Our business partners to offer You certain products, services or promotions." },
          { term: "With other users", text: "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside." },
          { term: "With Your consent", text: "We may disclose Your personal information for any other purpose with Your consent." },
        ],
      },
    ],
  },
  {
    heading: "Retention of Your Personal Data",
    blocks: [
      {
        type: "p",
        text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
      },
      {
        type: "p",
        text: "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
      },
    ],
  },
  {
    heading: "Transfer of Your Personal Data",
    blocks: [
      {
        type: "p",
        text: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
      },
      {
        type: "p",
        text: "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
      },
      {
        type: "p",
        text: "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
      },
    ],
  },
  {
    heading: "Disclosure of Your Personal Data",
    blocks: [
      { type: "h3", text: "Business Transactions" },
      {
        type: "p",
        text: "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
      },
      { type: "h3", text: "Law enforcement" },
      {
        type: "p",
        text: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
      },
      { type: "h3", text: "Other legal requirements" },
      {
        type: "p",
        text: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
      },
      {
        type: "list",
        items: [
          "Comply with a legal obligation",
          "Protect and defend the rights or property of the Company",
          "Prevent or investigate possible wrongdoing in connection with the Service",
          "Protect the personal safety of Users of the Service or the public",
          "Protect against legal liability",
        ],
      },
    ],
  },
  {
    heading: "Security of Your Personal Data",
    blocks: [
      {
        type: "p",
        text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      },
    ],
  },
  {
    heading: "Children's Privacy",
    blocks: [
      {
        type: "p",
        text: "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
      },
      {
        type: "p",
        text: "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
      },
    ],
  },
  {
    heading: "Links to Other Websites",
    blocks: [
      {
        type: "p",
        text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
      },
      {
        type: "p",
        text: "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
      },
    ],
  },
  {
    heading: "Changes to this Privacy Policy",
    blocks: [
      {
        type: "p",
        text: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
      },
      {
        type: "p",
        text: "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.",
      },
      {
        type: "p",
        text: "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
      },
    ],
  },
]

function BlockView({ block }: { block: Block }) {
  switch (block.type) {
    case "h3":
      return <h3 className="mt-8 text-lg font-semibold text-foreground">{block.text}</h3>
    case "p":
      return <p className="text-muted-foreground leading-relaxed">{block.text}</p>
    case "list":
      return (
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground leading-relaxed marker:text-green-600">
          {block.items.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      )
    case "defs":
      return (
        <ul className="space-y-3 text-muted-foreground leading-relaxed">
          {block.items.map((item, i) => (
            <li key={i} className="border-l-2 border-green-600/60 pl-4">
              <span className="font-semibold text-foreground">{item.term}:</span> {item.text}
            </li>
          ))}
        </ul>
      )
  }
}

export default function PrivacyPage() {
  return (
    <>
      {/* ============================ HERO ============================ */}
      <section className="relative min-h-[45vh] overflow-hidden">
        <div className="absolute inset-0">
          <img
            src={HERO_IMAGE}
            alt=""
            aria-hidden
            className="h-full w-full object-cover object-center"
          />
          <div className="absolute inset-0 bg-black/50" />
          <div className="absolute inset-0 bg-gradient-to-r from-black/75 via-black/45 to-transparent" />
        </div>

        <div className="relative z-10 mx-auto flex min-h-[45vh] max-w-7xl items-center px-4 py-20 sm:px-6 lg:px-8">
          <div className="max-w-2xl">
            <p className="text-xs font-semibold uppercase tracking-widest text-green-400">
              Legal
            </p>
            <div className="mt-4 h-px w-full origin-left bg-white/40" />
            <h1 className="mt-6 text-3xl sm:text-4xl md:text-5xl font-elegant thin tracking-wide text-white">
              Privacy Policy
            </h1>
            <p className="mt-6 max-w-xl text-base leading-relaxed text-white/85">
              How we collect, use, and safeguard your personal and research data.
            </p>
          </div>
        </div>
      </section>
      <section className="bg-background py-16 lg:py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            Last updated: {lastUpdated}
          </p>
          <div className="mt-12 space-y-12">
            {sections.map((section, i) => (
              <div key={section.heading}>
                <h2 className="font-serif text-2xl font-medium text-foreground">
                  {i + 1}. {section.heading}
                </h2>
                <div className="mt-4 space-y-4">
                  {section.blocks.map((block, j) => (
                    <BlockView key={j} block={block} />
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
